### ISSUE TITLE
FEE - Deselect file and delete file do not work

### ISSUE THREAD

**Issue by stu2019** [MetaModels/attribute_file#98] opened 2021-04-07 17:35 UTC
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      7.4.16    |                                  |
| Contao version:                     |     4.9.13     |                                  |
| MetaModels version:                 |     2.2@dev     |                                  |
| Installation via composer           | (yes) |                                  |
| Installed MetaModels packages       |     all     |                                  |

## Issue description
In FEE the checkboxes deselect (Zurücksetzen) and delete (Löschen) do not do anything

## Steps to reproduce
Check deselect and delete in Metamodels Eingabemaske.
Use FEE in the Browser, check deselect or delete.
Save.

## Describe the behaviour of the application
The page is updated, but nothing changed.

## Describe the expected behaviour of the application
The file should be removed from the record (and from files).

## Screenshots

https://user-images.githubusercontent.com/49641522/113909704-461d7d80-97d8-11eb-9ce1-36a6238d1f3d.mov

<img width="1314" alt="Bildschirmfoto 2021-04-07 um 18 48 15" src="https://user-images.githubusercontent.com/49641522/113909793-62211f00-97d8-11eb-9e19-2e03d1d8f36e.png">

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment] 2021-04-07 17:47
depends/duplicate of https://github.com/MetaModels/attribute_file/issues/92 ?

**Comment by zonky2** [comment] 2023-07-04 06:40
works at MM 2.3

Note: FEE with single is marked as deprecated - use multiple file and restricted at 1 file to upload

**Closed by zonky2** 2023-07-04 06:40 UTC
Labels: bug
