### ISSUE TITLE
If the Target Folder is not set the File upload in FEE throws an error

### ISSUE THREAD

**Issue by stu2019** [MetaModels/attribute_file#99] opened 2021-04-07 17:53 UTC
<img width="960" alt="Bildschirmfoto 2021-04-07 um 19 36 47" src="https://user-images.githubusercontent.com/49641522/113910028-a9a7ab00-97d8-11eb-8cc4-e81e2fb1edc5.png">
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_file/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      7.4.16    |                                  |
| Contao version:                     |     4.9.13     |                                  |
| MetaModels version:                 |     2.2@dev     |                                  |
| Installation via composer           | (yes) |                                  |
| Installed MetaModels packages       |     all     |                                  |

## Issue description

If the Target Folder is not set the File upload in FEE throws an error

## Steps to reproduce
In MM File Attribute check Mehrfachauswahl
In MM Eingabemaske the Initial Status for the file upload settings is 
- Use home directory unchecked
- Target folder: nothing is chosen
Go to the FEE and try to upload a file / image

## Describe the behaviour of the application
Get an error message

## Describe the expected behaviour of the application
An default target folder should be defined, so no error pops up.

## Screenshots
<img width="960" alt="Bildschirmfoto 2021-04-07 um 19 36 47" src="https://user-images.githubusercontent.com/49641522/113910924-a95bdf80-97d9-11eb-90ec-1e0d50efc506.png">
<img width="960" alt="Bildschirmfoto 2021-04-07 um 19 39 17" src="https://user-images.githubusercontent.com/49641522/113910948-ae209380-97d9-11eb-99a7-92984d4ff5e2.png">

https://user-images.githubusercontent.com/49641522/113911734-9695da80-97da-11eb-8122-f2a23c818d34.mov

[prod-2021-04-07.log](https://github.com/MetaModels/attribute_file/files/6273601/prod-2021-04-07.log)

(Add some visual love or even a video if you can)

**Comment by zonky2** [comment] 2021-04-07 17:54
please check open issues...

duplicate of https://github.com/MetaModels/attribute_file/issues/93

**Closed by zonky2** 2021-04-07 17:54 UTC
